AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-aws-basic-template-01

  Sample SAM Template for sam-aws-basic-template-01
  
# Variables que definen todas las caracteristicas "Globales para las funciones por ejemplo"
Globals:
  Function:
    Timeout: 3
    MemorySize: 128 
    Architectures: x86_64

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # Se define el recurso como Funcion Serverless
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x 
     
      Events:
        HelloWorld:
          Type: Api # Define el API GATEWAY, el recurso y el metodo
          Properties:
            Path: /hello
            Method: get

Outputs:
 
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
